// Code generated by tools/warp-gen. DO NOT EDIT.

package tools

import (
	"fmt"

	"github.com/masterkeysrd/loom/tool"
	"github.com/masterkeysrd/warp"
)

// LoomTools returns all builtin tools as Loom tools.
func LoomTools(handlers *ToolHandlers) ([]*tool.Tool, error) {
	resources, err := Resources()
	if err != nil {
		return nil, fmt.Errorf("failed to load tool resources: %w", err)
	}

	nameMap := make(map[string]*warp.Tool)
	for _, r := range resources {
		nameMap[r.Metadata.Name] = r
	}

	var list []*tool.Tool
	if res, ok := nameMap["activate_skill"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"activate_skill",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.ActivateSkill,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool activate_skill: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["ask_question"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"ask_question",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.AskQuestion,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool ask_question: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["bash"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.NewStreaming(
			"bash",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Bash,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool bash: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["download"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"download",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Download,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool download: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["edit"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"edit",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Edit,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool edit: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["fetch"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"fetch",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Fetch,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool fetch: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["glob"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"glob",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Glob,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool glob: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["grep"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"grep",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Grep,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool grep: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["invoke_agent"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.NewStreaming(
			"invoke_agent",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.InvokeAgent,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool invoke_agent: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["ls"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"ls",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Ls,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool ls: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["lsp_diagnostics"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"lsp_diagnostics",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.LspDiagnostics,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_diagnostics: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["lsp_inspect"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"lsp_inspect",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.LspInspect,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_inspect: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["lsp_restart"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"lsp_restart",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.LspRestart,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_restart: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["lsp_symbols"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"lsp_symbols",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.LspSymbols,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_symbols: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["mcp_list_resources"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"mcp_list_resources",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.McpListResources,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool mcp_list_resources: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["mcp_read_resources"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"mcp_read_resources",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.McpReadResources,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool mcp_read_resources: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["multi_edit"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"multi_edit",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.MultiEdit,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool multi_edit: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["remove"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"remove",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Remove,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool remove: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["schedule"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"schedule",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Schedule,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool schedule: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["tasks"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"tasks",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Tasks,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool tasks: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["todos"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"todos",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Todos,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool todos: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["view"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"view",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.View,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool view: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["web_fetch"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"web_fetch",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.WebFetch,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool web_fetch: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["web_search"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"web_search",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.WebSearch,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool web_search: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := nameMap["write"]; ok {
		var opts []tool.Option
		if res.Spec.Annotations != nil {
			opts = append(opts, tool.WithAnnotation(tool.Annotation{
				IsOpenWorld:  res.Spec.Annotations.IsOpenWorld,
				IsDangerous:  res.Spec.Annotations.IsDangerous,
				IsReadOnly:   res.Spec.Annotations.IsReadOnly,
				IsIdempotent: res.Spec.Annotations.IsIdempotent,
				UserHint:     res.Spec.Annotations.UserHint,
			}))
		}
		t, err := tool.New(
			"write",
			res.Metadata.DisplayName,
			res.Spec.Instructions,
			handlers.Write,
			opts...,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool write: %w", err)
		}
		list = append(list, t)
	}

	return list, nil
}
