// Code generated by tools/warp-gen. DO NOT EDIT.

package tools

import (
	"fmt"

	"github.com/masterkeysrd/loom/tool"
	"github.com/masterkeysrd/warp"
)

// LoomTools returns all builtin tools as Loom tools.
func LoomTools(handlers *ToolHandlers) ([]*tool.Tool, error) {
	resources, err := Resources()
	if err != nil {
		return nil, fmt.Errorf("failed to load tool resources: %w", err)
	}

	resMap := make(map[string]*warp.Tool)
	for _, r := range resources {
		resMap[r.Metadata.Name] = r
	}

	var list []*tool.Tool
	if res, ok := resMap["bash"]; ok {
		t, err := tool.New(
			"bash",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Bash,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool bash: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["download"]; ok {
		t, err := tool.New(
			"download",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Download,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool download: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["edit"]; ok {
		t, err := tool.New(
			"edit",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Edit,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool edit: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["fetch"]; ok {
		t, err := tool.New(
			"fetch",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Fetch,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool fetch: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["glob"]; ok {
		t, err := tool.New(
			"glob",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Glob,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool glob: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["grep"]; ok {
		t, err := tool.New(
			"grep",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Grep,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool grep: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["ls"]; ok {
		t, err := tool.New(
			"ls",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Ls,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool ls: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["lsp_diagnostics"]; ok {
		t, err := tool.New(
			"lsp_diagnostics",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.LspDiagnostics,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_diagnostics: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["lsp_restart"]; ok {
		t, err := tool.New(
			"lsp_restart",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.LspRestart,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_restart: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["lsp_search"]; ok {
		t, err := tool.New(
			"lsp_search",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.LspSearch,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool lsp_search: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["mcp_read_resources"]; ok {
		t, err := tool.New(
			"mcp_read_resources",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.McpReadResources,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool mcp_read_resources: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["multi_edit"]; ok {
		t, err := tool.New(
			"multi_edit",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.MultiEdit,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool multi_edit: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["remove"]; ok {
		t, err := tool.New(
			"remove",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Remove,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool remove: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["view"]; ok {
		t, err := tool.New(
			"view",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.View,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool view: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["web_fetch"]; ok {
		t, err := tool.New(
			"web_fetch",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.WebFetch,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool web_fetch: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["web_search"]; ok {
		t, err := tool.New(
			"web_search",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.WebSearch,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool web_search: %w", err)
		}
		list = append(list, t)
	}

	if res, ok := resMap["write"]; ok {
		t, err := tool.New(
			"write",
			res.Metadata.DisplayName,
			res.Metadata.Description,
			handlers.Write,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to create tool write: %w", err)
		}
		list = append(list, t)
	}

	return list, nil
}
