// Code generated by tools/warp-gen. DO NOT EDIT.

package tools

// BashArgs defines the arguments for the "bash" tool.
//
// Execute a bash command.
type BashArgs struct {
	// Command: Bash command to execute.
	Command string `json:"command" jsonschema:"Bash command to execute."`
}

// BashOutput defines the output returned by the "bash" tool.
type BashOutput struct {
	// ExitCode: Exit code.
	ExitCode int `json:"exitCode,omitempty" jsonschema:"Exit code."`
	// Stderr: Standard error.
	Stderr string `json:"stderr,omitempty" jsonschema:"Standard error."`
	// Stdout: Standard output.
	Stdout string `json:"stdout,omitempty" jsonschema:"Standard output."`
}

// DownloadArgs defines the arguments for the "download" tool.
//
// Download a file from a URL.
type DownloadArgs struct {
	// Url: URL to download from.
	Url string `json:"url" jsonschema:"URL to download from."`
}

// DownloadOutput defines the output returned by the "download" tool.
type DownloadOutput struct {
	// Path: Path to the downloaded file.
	Path string `json:"path,omitempty" jsonschema:"Path to the downloaded file."`
	// Success: Whether the download succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether the download succeeded."`
}

// EditArgs defines the arguments for the "edit" tool.
//
// Edit a file using sed.
type EditArgs struct {
	// Expression: Sed expression.
	Expression string `json:"expression" jsonschema:"Sed expression."`
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
}

// EditOutput defines the output returned by the "edit" tool.
type EditOutput struct {
	// Path: Path to the edited file.
	Path string `json:"path,omitempty" jsonschema:"Path to the edited file."`
	// Success: Whether the edit succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether the edit succeeded."`
}

// FetchArgs defines the arguments for the "fetch" tool.
//
// Fetch a URL.
type FetchArgs struct {
	// Url: URL to fetch.
	Url string `json:"url" jsonschema:"URL to fetch."`
}

// FetchOutput defines the output returned by the "fetch" tool.
type FetchOutput struct {
	// Content: Content of the response.
	Content string `json:"content,omitempty" jsonschema:"Content of the response."`
	// Status: HTTP status code.
	Status int `json:"status,omitempty" jsonschema:"HTTP status code."`
}

// GlobArgs defines the arguments for the "glob" tool.
//
// Find files matching a glob pattern.
type GlobArgs struct {
	// Pattern: Glob pattern to match.
	Pattern string `json:"pattern" jsonschema:"Glob pattern to match."`
}

// GlobOutput defines the output returned by the "glob" tool.
type GlobOutput struct {
	// Matches: List of matching file paths.
	Matches []string `json:"matches,omitempty" jsonschema:"List of matching file paths."`
}

// GrepArgs defines the arguments for the "grep" tool.
//
// Search for a pattern in files.
type GrepArgs struct {
	// Path: Directory or file to search in.
	Path string `json:"path" jsonschema:"Directory or file to search in."`
	// Pattern: Regex pattern to search for.
	Pattern string `json:"pattern" jsonschema:"Regex pattern to search for."`
}

// GrepOutput defines the output returned by the "grep" tool.
type GrepOutput struct {
	// Matches: List of search matches.
	Matches []any `json:"matches,omitempty" jsonschema:"List of search matches."`
}

// LsArgs defines the arguments for the "ls" tool.
//
// List files in a directory in ls -l format.
//
// Entries are filtered using a two-tier ignore system:
// 1. **Predefined ignores**: `.git`, `.env`, `node_modules`, `__pycache__`, `vendor`, `dist`, `build`, `target`, `.next`, `.nuxt`, `.DS_Store`, `.venv`, `venv`, `coverage`, and similar noise directories are always excluded.
// 2. **Gitignore rules**: if the target path is inside a git repository, all `.gitignore` files from the repo root down to the target directory are loaded and applied (full git semantics including nested `.gitignore` files).
//
// Use `pattern` to narrow results by filename glob and `type` to restrict to files, directories, or symlinks. Use `limit` (default 200) and check `truncated` + `total_count` to paginate large directories.
type LsArgs struct {
	// Limit: Maximum number of entries to return. Defaults to 200.
	Limit int `json:"limit,omitempty" jsonschema:"Maximum number of entries to return. Defaults to 200."`
	// Path: Path to the directory to list.
	Path string `json:"path" jsonschema:"Path to the directory to list."`
	// Pattern: Optional glob pattern to filter entries by name (e.g. "*.go", "test_*").
	Pattern string `json:"pattern,omitempty" jsonschema:"Optional glob pattern to filter entries by name (e.g. \"*.go\", \"test_*\")."`
	// Type: Optional entry type filter. One of "file", "dir", or "symlink".
	Type string `json:"type,omitempty" jsonschema:"Optional entry type filter. One of \"file\", \"dir\", or \"symlink\"."`
}

// LsOutput defines the output returned by the "ls" tool.
type LsOutput struct {
	// Files: List of matching directory entries, after filtering and ignore rules.
	Files []any `json:"files,omitempty" jsonschema:"List of matching directory entries, after filtering and ignore rules."`
	// TotalCount: Total number of entries after applying ignore and type/pattern filters.
	TotalCount int `json:"total_count,omitempty" jsonschema:"Total number of entries after applying ignore and type/pattern filters."`
	// Truncated: True when the result was capped by the limit and more entries exist.
	Truncated bool `json:"truncated,omitempty" jsonschema:"True when the result was capped by the limit and more entries exist."`
}

// LspDiagnosticsArgs defines the arguments for the "lsp_diagnostics" tool.
//
// Get LSP diagnostics.
type LspDiagnosticsArgs struct {
	// Path: Path to the file or directory.
	Path string `json:"path" jsonschema:"Path to the file or directory."`
}

// LspDiagnosticsOutput defines the output returned by the "lsp_diagnostics" tool.
type LspDiagnosticsOutput struct {
	// Diagnostics: List of LSP diagnostics.
	Diagnostics []any `json:"diagnostics,omitempty" jsonschema:"List of LSP diagnostics."`
}

// LspRestartArgs defines the arguments for the "lsp_restart" tool.
//
// Restart LSP server.
type LspRestartArgs struct {
	// Server: Name of the LSP server to restart.
	Server string `json:"server" jsonschema:"Name of the LSP server to restart."`
}

// LspRestartOutput defines the output returned by the "lsp_restart" tool.
type LspRestartOutput struct {
	// Message: Description of the restart outcome.
	Message string `json:"message,omitempty" jsonschema:"Description of the restart outcome."`
	// Success: Whether the LSP server restarted successfully.
	Success bool `json:"success,omitempty" jsonschema:"Whether the LSP server restarted successfully."`
}

// LspSearchArgs defines the arguments for the "lsp_search" tool.
//
// Search using LSP.
type LspSearchArgs struct {
	// Query: Search query.
	Query string `json:"query" jsonschema:"Search query."`
}

// LspSearchOutput defines the output returned by the "lsp_search" tool.
type LspSearchOutput struct {
	// Results: List of LSP search results.
	Results []any `json:"results,omitempty" jsonschema:"List of LSP search results."`
}

// McpReadResourcesArgs defines the arguments for the "mcp_read_resources" tool.
//
// Read resources from MCP.
type McpReadResourcesArgs struct {
	// Uri: MCP resource URI.
	Uri string `json:"uri" jsonschema:"MCP resource URI."`
}

// McpReadResourcesOutput defines the output returned by the "mcp_read_resources" tool.
type McpReadResourcesOutput struct {
	// Content: Content of the MCP resource.
	Content string `json:"content,omitempty" jsonschema:"Content of the MCP resource."`
	// Success: Whether reading the resource succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether reading the resource succeeded."`
}

// RemoveArgs defines the arguments for the "remove" tool.
//
// Remove a file or directory.
type RemoveArgs struct {
	// Path: Path to remove.
	Path string `json:"path" jsonschema:"Path to remove."`
}

// RemoveOutput defines the output returned by the "remove" tool.
type RemoveOutput struct {
	// Path: Path that was removed.
	Path string `json:"path,omitempty" jsonschema:"Path that was removed."`
	// Success: Whether removal succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether removal succeeded."`
}

// ViewArgs defines the arguments for the "view" tool.
//
// Reads the contents of a file.
//
// Important Usage Rules:
// - Large files will be automatically truncated to fit your context window.
// - Extremely long single lines (like base64 strings or minified code) will be automatically omitted to protect your context.
// - If the output ends with a [SYSTEM NOTE] stating the file was truncated, do not assume you have the full file context. You must call `view` again using the `start_line` parameter provided in the system note to paginate and read the remainder of the file before making final decisions or edits.
type ViewArgs struct {
	// EndLine: The 1-indexed line number to stop reading at (optional).
	EndLine int `json:"end_line,omitempty" jsonschema:"The 1-indexed line number to stop reading at (optional)."`
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
	// StartLine: The 1-indexed line number to start reading from (optional, defaults to 1).
	StartLine int `json:"start_line,omitempty" jsonschema:"The 1-indexed line number to start reading from (optional, defaults to 1)."`
}

// ViewOutput defines the output returned by the "view" tool.
type ViewOutput struct {
	// CachedPath: Cached path in workspace session storage.
	CachedPath string `json:"cached_path,omitempty" jsonschema:"Cached path in workspace session storage."`
	// Content: Content of the file.
	Content string `json:"content,omitempty" jsonschema:"Content of the file."`
	// EndLine: The end line of the returned content.
	EndLine int `json:"end_line,omitempty" jsonschema:"The end line of the returned content."`
	// IsBinary: Whether the file is binary.
	IsBinary bool `json:"is_binary,omitempty" jsonschema:"Whether the file is binary."`
	// MimeType: Detected MIME type of the file.
	MimeType string `json:"mime_type,omitempty" jsonschema:"Detected MIME type of the file."`
	// Path: Path to the file.
	Path string `json:"path,omitempty" jsonschema:"Path to the file."`
	// StartLine: The start line of the returned content.
	StartLine int `json:"start_line,omitempty" jsonschema:"The start line of the returned content."`
	// TotalLines: Total number of lines in the file.
	TotalLines int `json:"total_lines,omitempty" jsonschema:"Total number of lines in the file."`
	// Truncated: Whether the file content was truncated due to size limits.
	Truncated bool `json:"truncated,omitempty" jsonschema:"Whether the file content was truncated due to size limits."`
}

// WebFetchArgs defines the arguments for the "web_fetch" tool.
//
// Fetch a web page content.
type WebFetchArgs struct {
	// Url: Web page URL.
	Url string `json:"url" jsonschema:"Web page URL."`
}

// WebFetchOutput defines the output returned by the "web_fetch" tool.
type WebFetchOutput struct {
	// Content: Web page content.
	Content string `json:"content,omitempty" jsonschema:"Web page content."`
	// Title: Web page title.
	Title string `json:"title,omitempty" jsonschema:"Web page title."`
}

// WebSearchArgs defines the arguments for the "web_search" tool.
//
// Search the web.
type WebSearchArgs struct {
	// Query: Search query.
	Query string `json:"query" jsonschema:"Search query."`
}

// WebSearchOutput defines the output returned by the "web_search" tool.
type WebSearchOutput struct {
	// Results: Search results.
	Results []any `json:"results,omitempty" jsonschema:"Search results."`
}

// WriteArgs defines the arguments for the "write" tool.
//
// Write content to a file.
type WriteArgs struct {
	// Content: Content to write.
	Content string `json:"content" jsonschema:"Content to write."`
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
}

// WriteOutput defines the output returned by the "write" tool.
type WriteOutput struct {
	// Path: Path to the written file.
	Path string `json:"path,omitempty" jsonschema:"Path to the written file."`
}
