// Code generated by tools/warp-gen. DO NOT EDIT.

package tools

// ActivateSkillArgs defines the arguments for the "activate_skill" tool.
//
// # Activate Skill
//
// Use this tool to dynamically load specialized domain-specific instructions, conventions, style guides, and scripts into your conversation context.
//
// ## When to Call
// - Look at the **Available Skills** section in your system prompt. Every skill lists a name and a description that acts as a trigger.
// - If your current objective or any subtask involves the concepts mentioned in a skill's trigger description, you **MUST** call `activate_skill` to load its instructions before proceeding with the task.
// - Call this tool early in your plan so that the guidelines are active when you write code.
//
// ## Interpreting Output
// - This tool returns the full rendered text of the skill's instructions, which will automatically be injected into your conversation history. Read these instructions carefully.
// - The tool also returns the absolute directory `path` where the skill is located. You can run scripts from its `scripts/` directory or read files from its `references/` or `assets/` subdirectories by using standard shell/view tools relative to this absolute path.
type ActivateSkillArgs struct {
	// Skill: The name of the skill to activate (e.g. 'git-expert').
	Skill string `json:"skill" jsonschema:"The name of the skill to activate (e.g. 'git-expert')."`
}

// ActivateSkillOutput defines the output returned by the "activate_skill" tool.
type ActivateSkillOutput struct {
	// Instructions: The rendered instructions and guidelines of the activated skill.
	Instructions string `json:"instructions,omitempty" jsonschema:"The rendered instructions and guidelines of the activated skill."`
	// Message: A human-readable result or error message.
	Message string `json:"message,omitempty" jsonschema:"A human-readable result or error message."`
	// Path: The absolute filesystem directory path where the skill's resources, scripts, and files are stored.
	Path string `json:"path,omitempty" jsonschema:"The absolute filesystem directory path where the skill's resources, scripts, and files are stored."`
	// Success: Whether the skill was successfully activated.
	Success bool `json:"success,omitempty" jsonschema:"Whether the skill was successfully activated."`
}

// BashArgs defines the arguments for the "bash" tool.
//
// Execute a bash command. If it takes longer than wait_ms, it automatically transitions to a background task.
//
// IMPORTANT: Do NOT run commands in the background of the shell yourself (e.g. by appending '&' or using background commands). The TaskManager handles background execution automatically. If you background the command yourself, the TaskManager will immediately mark it as finished and lose track of it, preventing you from managing or stopping it.
type BashArgs struct {
	// Command: Bash command to execute.
	Command string `json:"command" jsonschema:"Bash command to execute."`
	// Description: A short description of what you are trying to accomplish by running this command.
	Description string `json:"description" jsonschema:"A short description of what you are trying to accomplish by running this command."`
	// Timeout: Maximum duration (in seconds) for the command execution before forced termination.
	Timeout int `json:"timeout,omitempty" jsonschema:"Maximum duration (in seconds) for the command execution before forced termination."`
	// WaitMs: Time (in milliseconds) to wait for synchronous completion before shifting to background execution. Defaults to 10000.
	WaitMs int `json:"wait_ms,omitempty" jsonschema:"Time (in milliseconds) to wait for synchronous completion before shifting to background execution. Defaults to 10000."`
}

// BashOutput defines the output returned by the "bash" tool.
type BashOutput struct {
	// ExitCode: Exit code of the command (if finished synchronously).
	ExitCode int `json:"exitCode,omitempty" jsonschema:"Exit code of the command (if finished synchronously)."`
	// Message: A human-readable description of the execution status.
	Message string `json:"message,omitempty" jsonschema:"A human-readable description of the execution status."`
	// Status: The current status of the task ('running', 'completed', 'failed', 'killed').
	Status string `json:"status,omitempty" jsonschema:"The current status of the task ('running', 'completed', 'failed', 'killed')."`
	// Stderr: Standard error of the command (if finished synchronously).
	Stderr string `json:"stderr,omitempty" jsonschema:"Standard error of the command (if finished synchronously)."`
	// Stdout: Standard output of the command (if finished synchronously).
	Stdout string `json:"stdout,omitempty" jsonschema:"Standard output of the command (if finished synchronously)."`
	// TaskId: The ID of the background task if execution transitioned to background.
	TaskId string `json:"taskId,omitempty" jsonschema:"The ID of the background task if execution transitioned to background."`
}

// DownloadArgs defines the arguments for the "download" tool.
//
// Download a file from a URL. If it takes longer than wait_ms, it automatically transitions to a background task.
type DownloadArgs struct {
	// Destination: Local file path to save the downloaded file (optional, defaults to the filename in the URL in workspace root).
	Destination string `json:"destination,omitempty" jsonschema:"Local file path to save the downloaded file (optional, defaults to the filename in the URL in workspace root)."`
	// Url: URL to download from.
	Url string `json:"url" jsonschema:"URL to download from."`
	// WaitMs: Time (in milliseconds) to wait for synchronous completion before shifting to background execution. Defaults to 5000.
	WaitMs int `json:"wait_ms,omitempty" jsonschema:"Time (in milliseconds) to wait for synchronous completion before shifting to background execution. Defaults to 5000."`
}

// DownloadOutput defines the output returned by the "download" tool.
type DownloadOutput struct {
	// Message: A human-readable description of the execution status.
	Message string `json:"message,omitempty" jsonschema:"A human-readable description of the execution status."`
	// Path: Path to the downloaded file.
	Path string `json:"path,omitempty" jsonschema:"Path to the downloaded file."`
	// SizeBytes: Size of the downloaded file.
	SizeBytes int `json:"size_bytes,omitempty" jsonschema:"Size of the downloaded file."`
	// Success: Whether the download succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether the download succeeded."`
	// TaskId: The ID of the background task if execution transitioned to background.
	TaskId string `json:"taskId,omitempty" jsonschema:"The ID of the background task if execution transitioned to background."`
}

// EditArgs defines the arguments for the "edit" tool.
//
// Edit a file by replacing a target block of text with a replacement block.
type EditArgs struct {
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
	// ReplaceAll: If true, replaces all occurrences of the target block. If false (default), fails if the target block is not unique.
	ReplaceAll bool `json:"replace_all,omitempty" jsonschema:"If true, replaces all occurrences of the target block. If false (default), fails if the target block is not unique."`
	// Replacement: The replacement content for the target block.
	Replacement string `json:"replacement" jsonschema:"The replacement content for the target block."`
	// Target: The exact block of code to edit. This must match a unique sequence of lines in the existing file.
	Target string `json:"target" jsonschema:"The exact block of code to edit. This must match a unique sequence of lines in the existing file."`
}

// EditOutput defines the output returned by the "edit" tool.
type EditOutput struct {
	// Additions: The number of lines added.
	Additions int `json:"additions,omitempty" jsonschema:"The number of lines added."`
	// Deletions: The number of lines deleted.
	Deletions int `json:"deletions,omitempty" jsonschema:"The number of lines deleted."`
	// Diff: The unified diff showing the changes made.
	Diff string `json:"diff,omitempty" jsonschema:"The unified diff showing the changes made."`
	// FullDiff: The full untruncated unified diff.
	FullDiff string `json:"-" jsonschema:"The full untruncated unified diff."`
	// Message: Error or status message if the edit failed.
	Message string `json:"message,omitempty" jsonschema:"Error or status message if the edit failed."`
	// Path: Path to the edited file.
	Path string `json:"path,omitempty" jsonschema:"Path to the edited file."`
	// Success: Whether the edit succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether the edit succeeded."`
}

// FetchArgs defines the arguments for the "fetch" tool.
//
// Fetch a URL.
type FetchArgs struct {
	// Format: Output format. Must be one of text, markdown, html. Defaults to text.
	Format string `json:"format,omitempty" jsonschema:"Output format. Must be one of text, markdown, html. Defaults to text."`
	// Timeout: Request timeout in seconds (up to 120). Defaults to 30.
	Timeout int `json:"timeout,omitempty" jsonschema:"Request timeout in seconds (up to 120). Defaults to 30."`
	// Url: URL to fetch.
	Url string `json:"url" jsonschema:"URL to fetch."`
}

// FetchOutput defines the output returned by the "fetch" tool.
type FetchOutput struct {
	// CachedPath: Cached path in workspace session storage.
	CachedPath string `json:"cached_path,omitempty" jsonschema:"Cached path in workspace session storage."`
	// Content: Content of the response.
	Content string `json:"content,omitempty" jsonschema:"Content of the response."`
	// Status: HTTP status code.
	Status int `json:"status,omitempty" jsonschema:"HTTP status code."`
	// Truncated: Whether the content was truncated due to context limits.
	Truncated bool `json:"truncated,omitempty" jsonschema:"Whether the content was truncated due to context limits."`
}

// GlobArgs defines the arguments for the "glob" tool.
//
// Find files matching a glob pattern.
type GlobArgs struct {
	// Path: Base directory to search from. Defaults to the workspace directory.
	Path string `json:"path,omitempty" jsonschema:"Base directory to search from. Defaults to the workspace directory."`
	// Pattern: Glob pattern to match.
	Pattern string `json:"pattern" jsonschema:"Glob pattern to match."`
}

// GlobOutput defines the output returned by the "glob" tool.
type GlobOutput struct {
	// Matches: List of matching file paths.
	Matches []string `json:"matches,omitempty" jsonschema:"List of matching file paths."`
	// TotalCount: Total number of matches after applying ignore filters.
	TotalCount int `json:"total_count,omitempty" jsonschema:"Total number of matches after applying ignore filters."`
	// Truncated: True when the result was capped by the limit.
	Truncated bool `json:"truncated,omitempty" jsonschema:"True when the result was capped by the limit."`
}

// GrepArgs defines the arguments for the "grep" tool.
//
// Search for a pattern in files.
type GrepArgs struct {
	// Path: Directory or file to search in.
	Path string `json:"path" jsonschema:"Directory or file to search in."`
	// Pattern: Regex pattern to search for.
	Pattern string `json:"pattern" jsonschema:"Regex pattern to search for."`
}

// GrepOutput defines the output returned by the "grep" tool.
type GrepOutput struct {
	// Matches: List of search matches.
	Matches []GrepOutputMatchesItem `json:"matches,omitempty" jsonschema:"List of search matches."`
	// TotalCount: Total number of matches found.
	TotalCount int `json:"total_count,omitempty" jsonschema:"Total number of matches found."`
	// Truncated: True when the result was capped by the limit.
	Truncated bool `json:"truncated,omitempty" jsonschema:"True when the result was capped by the limit."`
}

type GrepOutputMatchesItem struct {
	// Content: Content of the matching line.
	Content string `json:"content,omitempty" jsonschema:"Content of the matching line."`
	// Line: 1-indexed line number of the match.
	Line int `json:"line,omitempty" jsonschema:"1-indexed line number of the match."`
	// Path: File path containing the match.
	Path string `json:"path,omitempty" jsonschema:"File path containing the match."`
}

// LsArgs defines the arguments for the "ls" tool.
//
// List files in a directory in ls -l format.
//
// Entries are filtered using a two-tier ignore system:
// 1. **Predefined ignores**: `.git`, `.env`, `node_modules`, `__pycache__`, `vendor`, `dist`, `build`, `target`, `.next`, `.nuxt`, `.DS_Store`, `.venv`, `venv`, `coverage`, and similar noise directories are always excluded.
// 2. **Gitignore rules**: if the target path is inside a git repository, all `.gitignore` files from the repo root down to the target directory are loaded and applied (full git semantics including nested `.gitignore` files).
//
// Use `pattern` to narrow results by filename glob and `type` to restrict to files, directories, or symlinks. Use `limit` (default 200) and check `truncated` + `total_count` to paginate large directories.
type LsArgs struct {
	// Limit: Maximum number of entries to return. Defaults to 200.
	Limit int `json:"limit,omitempty" jsonschema:"Maximum number of entries to return. Defaults to 200."`
	// Path: Path to the directory to list.
	Path string `json:"path" jsonschema:"Path to the directory to list."`
	// Pattern: Optional glob pattern to filter entries by name (e.g. "*.go", "test_*").
	Pattern string `json:"pattern,omitempty" jsonschema:"Optional glob pattern to filter entries by name (e.g. \"*.go\", \"test_*\")."`
	// Type: Optional entry type filter. One of "file", "dir", or "symlink".
	Type string `json:"type,omitempty" jsonschema:"Optional entry type filter. One of \"file\", \"dir\", or \"symlink\"."`
}

// LsOutput defines the output returned by the "ls" tool.
type LsOutput struct {
	// Files: List of matching directory entries, after filtering and ignore rules.
	Files []LsOutputFilesItem `json:"files,omitempty" jsonschema:"List of matching directory entries, after filtering and ignore rules."`
	// TotalCount: Total number of entries after applying ignore and type/pattern filters.
	TotalCount int `json:"total_count,omitempty" jsonschema:"Total number of entries after applying ignore and type/pattern filters."`
	// Truncated: True when the result was capped by the limit and more entries exist.
	Truncated bool `json:"truncated,omitempty" jsonschema:"True when the result was capped by the limit and more entries exist."`
}

type LsOutputFilesItem struct {
	// Group: Group name.
	Group string `json:"group,omitempty" jsonschema:"Group name."`
	// IsDir: Whether the entry is a directory.
	IsDir bool `json:"is_dir,omitempty" jsonschema:"Whether the entry is a directory."`
	// IsSymlink: Whether the entry is a symbolic link.
	IsSymlink bool `json:"is_symlink,omitempty" jsonschema:"Whether the entry is a symbolic link."`
	// LinkTarget: Symlink target path (only present when is_symlink is true).
	LinkTarget string `json:"link_target,omitempty" jsonschema:"Symlink target path (only present when is_symlink is true)."`
	// Links: Number of hard links.
	Links int `json:"links,omitempty" jsonschema:"Number of hard links."`
	// Modified: Last modification time (RFC3339).
	Modified string `json:"modified,omitempty" jsonschema:"Last modification time (RFC3339)."`
	// Name: File or directory name.
	Name string `json:"name,omitempty" jsonschema:"File or directory name."`
	// NameTruncated: Whether the name was truncated in the formatted field due to excessive length.
	NameTruncated bool `json:"name_truncated,omitempty" jsonschema:"Whether the name was truncated in the formatted field due to excessive length."`
	// Owner: Owner username.
	Owner string `json:"owner,omitempty" jsonschema:"Owner username."`
	// Permissions: File mode string (e.g. -rw-r--r-- or drwxr-xr-x).
	Permissions string `json:"permissions,omitempty" jsonschema:"File mode string (e.g. -rw-r--r-- or drwxr-xr-x)."`
	// Size: Size in bytes.
	Size int `json:"size,omitempty" jsonschema:"Size in bytes."`
}

// LspDiagnosticsArgs defines the arguments for the "lsp_diagnostics" tool.
//
// Get LSP diagnostics.
type LspDiagnosticsArgs struct {
	// Path: Path to the file or directory.
	Path string `json:"path" jsonschema:"Path to the file or directory."`
}

// LspDiagnosticsOutput defines the output returned by the "lsp_diagnostics" tool.
type LspDiagnosticsOutput struct {
	// Diagnostics: List of LSP diagnostics.
	Diagnostics []LspDiagnosticsOutputDiagnosticsItem `json:"diagnostics,omitempty" jsonschema:"List of LSP diagnostics."`
}

type LspDiagnosticsOutputDiagnosticsItem struct {
}

// LspRestartArgs defines the arguments for the "lsp_restart" tool.
//
// Restart LSP server.
type LspRestartArgs struct {
	// Server: Name of the LSP server to restart.
	Server string `json:"server" jsonschema:"Name of the LSP server to restart."`
}

// LspRestartOutput defines the output returned by the "lsp_restart" tool.
type LspRestartOutput struct {
	// Message: Description of the restart outcome.
	Message string `json:"message,omitempty" jsonschema:"Description of the restart outcome."`
	// Success: Whether the LSP server restarted successfully.
	Success bool `json:"success,omitempty" jsonschema:"Whether the LSP server restarted successfully."`
}

// LspSearchArgs defines the arguments for the "lsp_search" tool.
//
// Search using LSP.
type LspSearchArgs struct {
	// Query: Search query.
	Query string `json:"query" jsonschema:"Search query."`
}

// LspSearchOutput defines the output returned by the "lsp_search" tool.
type LspSearchOutput struct {
	// Results: List of LSP search results.
	Results []LspSearchOutputResultsItem `json:"results,omitempty" jsonschema:"List of LSP search results."`
}

type LspSearchOutputResultsItem struct {
}

// McpReadResourcesArgs defines the arguments for the "mcp_read_resources" tool.
//
// Read resources from MCP.
type McpReadResourcesArgs struct {
	// Uri: MCP resource URI.
	Uri string `json:"uri" jsonschema:"MCP resource URI."`
}

// McpReadResourcesOutput defines the output returned by the "mcp_read_resources" tool.
type McpReadResourcesOutput struct {
	// Content: Content of the MCP resource.
	Content string `json:"content,omitempty" jsonschema:"Content of the MCP resource."`
	// Success: Whether reading the resource succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether reading the resource succeeded."`
}

// MultiEditArgs defines the arguments for the "multi_edit" tool.
//
// Apply multiple, non-contiguous edits to a single file. This is highly useful for making multiple related changes across a file in a single turn.
type MultiEditArgs struct {
	// Edits: A list of edits to apply to the file.
	Edits []MultiEditArgsEditsItem `json:"edits" jsonschema:"A list of edits to apply to the file."`
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
}

type MultiEditArgsEditsItem struct {
	// ReplaceAll: If true, replaces all occurrences of the target block. If false (default), fails if the target block is not unique.
	ReplaceAll bool `json:"replace_all,omitempty" jsonschema:"If true, replaces all occurrences of the target block. If false (default), fails if the target block is not unique."`
	// Replacement: The replacement content for the target block.
	Replacement string `json:"replacement" jsonschema:"The replacement content for the target block."`
	// Target: The exact block of code to edit.
	Target string `json:"target" jsonschema:"The exact block of code to edit."`
}

// MultiEditOutput defines the output returned by the "multi_edit" tool.
type MultiEditOutput struct {
	// Additions: The total number of lines added.
	Additions int `json:"additions,omitempty" jsonschema:"The total number of lines added."`
	// Deletions: The total number of lines deleted.
	Deletions int `json:"deletions,omitempty" jsonschema:"The total number of lines deleted."`
	// Diff: The unified diff showing all successfully applied changes.
	Diff string `json:"diff,omitempty" jsonschema:"The unified diff showing all successfully applied changes."`
	// FullDiff: The full untruncated unified diff.
	FullDiff string `json:"-" jsonschema:"The full untruncated unified diff."`
	// Path: Path to the file.
	Path string `json:"path,omitempty" jsonschema:"Path to the file."`
	// Results: The status of each edit in the edits list.
	Results []MultiEditOutputResultsItem `json:"results,omitempty" jsonschema:"The status of each edit in the edits list."`
	// Success: Whether any edits were successfully applied.
	Success bool `json:"success,omitempty" jsonschema:"Whether any edits were successfully applied."`
}

type MultiEditOutputResultsItem struct {
	// Message: Failure reason if this specific edit failed.
	Message string `json:"message,omitempty" jsonschema:"Failure reason if this specific edit failed."`
	// Success: Whether this specific edit was applied.
	Success bool `json:"success" jsonschema:"Whether this specific edit was applied."`
}

// RemoveArgs defines the arguments for the "remove" tool.
//
// Remove a file or directory.
type RemoveArgs struct {
	// Path: Path to remove.
	Path string `json:"path" jsonschema:"Path to remove."`
	// Recursive: Must be set to true to remove directories recursively. Defaults to false.
	Recursive bool `json:"recursive,omitempty" jsonschema:"Must be set to true to remove directories recursively. Defaults to false."`
}

// RemoveOutput defines the output returned by the "remove" tool.
type RemoveOutput struct {
	// Content: The content of the deleted file.
	Content string `json:"content,omitempty" jsonschema:"The content of the deleted file."`
	// IsBinary: Whether the deleted file is binary.
	IsBinary bool `json:"is_binary,omitempty" jsonschema:"Whether the deleted file is binary."`
	// MimeType: The MIME type of the deleted file.
	MimeType string `json:"mime_type,omitempty" jsonschema:"The MIME type of the deleted file."`
	// Path: Path that was removed.
	Path string `json:"path,omitempty" jsonschema:"Path that was removed."`
	// Success: Whether removal succeeded.
	Success bool `json:"success,omitempty" jsonschema:"Whether removal succeeded."`
}

// TasksArgs defines the arguments for the "tasks" tool.
//
// Manage and monitor background tasks.
type TasksArgs struct {
	// Action: The action to perform. One of: 'list' (list all active and completed background tasks in the session), 'status' (retrieve the execution state and log tail of a specific task), 'kill' (terminate a running task).
	Action string `json:"action" jsonschema:"The action to perform. One of: 'list' (list all active and completed background tasks in the session), 'status' (retrieve the execution state and log tail of a specific task), 'kill' (terminate a running task)."`
	// Limit: The maximum number of lines from the end of the log to return for 'status' action (defaults to 100).
	Limit int `json:"limit,omitempty" jsonschema:"The maximum number of lines from the end of the log to return for 'status' action (defaults to 100)."`
	// TaskId: The ID of the background task (required for 'status' and 'kill').
	TaskId string `json:"taskId,omitempty" jsonschema:"The ID of the background task (required for 'status' and 'kill')."`
}

// TasksOutput defines the output returned by the "tasks" tool.
type TasksOutput struct {
	// ExitCode: The exit code of the requested task (if finished).
	ExitCode int `json:"exitCode,omitempty" jsonschema:"The exit code of the requested task (if finished)."`
	// Message: A human-readable result or error message.
	Message string `json:"message,omitempty" jsonschema:"A human-readable result or error message."`
	// Status: The status of the requested task.
	Status string `json:"status,omitempty" jsonschema:"The status of the requested task."`
	// StderrTail: The tail of the standard error log (for 'status' action).
	StderrTail string `json:"stderrTail,omitempty" jsonschema:"The tail of the standard error log (for 'status' action)."`
	// StdoutTail: The tail of the standard output log (for 'status' action).
	StdoutTail string `json:"stdoutTail,omitempty" jsonschema:"The tail of the standard output log (for 'status' action)."`
	// Tasks: List of background tasks (only returned for 'list' action).
	Tasks []TasksOutputTasksItem `json:"tasks,omitempty" jsonschema:"List of background tasks (only returned for 'list' action)."`
}

type TasksOutputTasksItem struct {
	// Details: Extra generic task execution details.
	Details string `json:"details,omitempty" jsonschema:"Extra generic task execution details."`
	// Error: Error message if the task failed.
	Error string `json:"error,omitempty" jsonschema:"Error message if the task failed."`
	// ExitCode: The exit code of the task (if finished).
	ExitCode int `json:"exitCode,omitempty" jsonschema:"The exit code of the task (if finished)."`
	// FinishedAt: Timestamp when the task finished.
	FinishedAt string `json:"finishedAt,omitempty" jsonschema:"Timestamp when the task finished."`
	// Name: The friendly name or command of the task.
	Name string `json:"name,omitempty" jsonschema:"The friendly name or command of the task."`
	// StartedAt: Timestamp when the task started.
	StartedAt string `json:"startedAt,omitempty" jsonschema:"Timestamp when the task started."`
	// Status: The current status of the task.
	Status string `json:"status,omitempty" jsonschema:"The current status of the task."`
	// TaskId: The ID of the task.
	TaskId string `json:"taskId,omitempty" jsonschema:"The ID of the task."`
	// Type: The type of task (e.g. bash).
	Type string `json:"type,omitempty" jsonschema:"The type of task (e.g. bash)."`
}

// TodosArgs defines the arguments for the "todos" tool.
//
// Manages a structured task list for multi-step work. Call this tool to create, update, or complete tasks. Every call **replaces the entire task list** — always include all existing tasks when making an update.
//
// ## How to Use
//
// Call the tool by providing an array of the **complete, updated list of tasks**. This list will overwrite the current task state entirely. Omitting a task from the array will permanently remove it. Only one task in_progress at the time to keep work focuses - Update inmediately after state changes for accurate tracking.
//
// ## When to Use
//
// Use this tool whenever:
// - A new task is identified or created
// - An existing task changes status (e.g., starts, completes, gets blocked)
// - A task is broken down into smaller subtasks
// - A task's description or `active_text` needs to be updated
// - After receiving new instructions to capture requirements
// - User provide multiples tasks (numbered, commands-separated list)
// - User request todos list management
// - Non-trivial tasks that requires careful planning and multiple operations
// - After completing a task (marking it `completed` and add a follow-up task if needed)
//
// ## When NOT to Use
//
// - Trivial task with not organization benefit
// - Purely conversational or informational interactions without actionable tasks
//
// ## Task Status Values
//
// | Status       | Meaning                                              |
// |--------------|------------------------------------------------------|
// | `pending`    | The task has not been started yet.                   |
// | `in_progress`| The task is actively being worked on.                |
// | `completed`  | The task is finished and all requirements are met.   |
//
// ## State Management
//
// The agent is the **single source of truth** for the task list. Every invocation of this tool replaces the entire list in application state. You must always pass every task — both unchanged ones and any newly added or modified ones.
//
// ## Completion Requirement
//
// A task may only be marked `completed` when **all** of its subtasks and associated requirements have been thoroughly verified and resolved. Do not mark a task complete prematurely.
//
// Never mark a task as `completed` if:
// - Tests or verification steps are failed or incomplete
// - Implementation is partial or missing critical components
// - Encountered unresolved errors or blockers that prevent full completion
// - Cannot find files or dependencies required to complete the task
//
// ## Handling Blockers or Failures
//
// If a task cannot proceed or fails, do not use a blocked state. Instead, create new todos with the tasks required to unblock the work. If you cannot complete the task, leave the todos in their current state and output to the user explaining the situation.
//
// ## Breaking Down Tasks
//
// Complex or large tasks must be decomposed into smaller, actionable subtasks. When a task is broken down, add the new subtasks to the array alongside the parent task (which may be left `in_progress` or removed, depending on context).
//
// **IMPORTANT**: Never print or list the todos in your response text. The users already have the full list of tasks in the application state.
type TodosArgs struct {
	// Todos: The complete, authoritative list of tasks. It replaces the current task list in its entirety on every update.
	Todos []TodosArgsTodosItem `json:"todos" jsonschema:"The complete, authoritative list of tasks. It replaces the current task list in its entirety on every update."`
}

type TodosArgsTodosItem struct {
	// ActiveText: Optional text describing the current activity for in_progress tasks, e.g. 'writing code' or 'waiting for response from database'.
	ActiveText string `json:"active_text,omitempty" jsonschema:"Optional text describing the current activity for in_progress tasks, e.g. 'writing code' or 'waiting for response from database'."`
	// Description: A brief description of the task.
	Description string `json:"description" jsonschema:"A brief description of the task."`
	// Status: The status of the task. Must be one of: 'pending', 'in_progress', 'completed'.
	Status string `json:"status" jsonschema:"The status of the task. Must be one of: 'pending', 'in_progress', 'completed'."`
}

// TodosOutput defines the output returned by the "todos" tool.
type TodosOutput struct {
	Todos []TodosOutputTodosItem `json:"todos,omitempty"`
}

type TodosOutputTodosItem struct {
	ActiveText  string `json:"active_text,omitempty"`
	Description string `json:"description,omitempty"`
	Status      string `json:"status,omitempty"`
}

// ViewArgs defines the arguments for the "view" tool.
//
// Reads the contents of a file.
//
// Important Usage Rules:
// - Large files will be automatically truncated to fit your context window.
// - Extremely long single lines (like base64 strings or minified code) will be automatically omitted to protect your context.
// - If the output ends with a [SYSTEM NOTE] stating the file was truncated, do not assume you have the full file context. You must call `view` again using the `start_line` parameter provided in the system note to paginate and read the remainder of the file before making final decisions or edits.
type ViewArgs struct {
	// EndLine: The 1-indexed line number to stop reading at (optional).
	EndLine int `json:"end_line,omitempty" jsonschema:"The 1-indexed line number to stop reading at (optional)."`
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
	// StartLine: The 1-indexed line number to start reading from (optional, defaults to 1).
	StartLine int `json:"start_line,omitempty" jsonschema:"The 1-indexed line number to start reading from (optional, defaults to 1)."`
}

// ViewOutput defines the output returned by the "view" tool.
type ViewOutput struct {
	// CachedPath: Cached path in workspace session storage.
	CachedPath string `json:"cached_path,omitempty" jsonschema:"Cached path in workspace session storage."`
	// Content: Content of the file.
	Content string `json:"content,omitempty" jsonschema:"Content of the file."`
	// EndLine: The end line of the returned content.
	EndLine int `json:"end_line,omitempty" jsonschema:"The end line of the returned content."`
	// IsBinary: Whether the file is binary.
	IsBinary bool `json:"is_binary,omitempty" jsonschema:"Whether the file is binary."`
	// MimeType: Detected MIME type of the file.
	MimeType string `json:"mime_type,omitempty" jsonschema:"Detected MIME type of the file."`
	// Source: The source path or resource.
	Source string `json:"source,omitempty" jsonschema:"The source path or resource."`
	// StartLine: The start line of the returned content.
	StartLine int `json:"start_line,omitempty" jsonschema:"The start line of the returned content."`
	// TotalLines: Total number of lines in the file.
	TotalLines int `json:"total_lines,omitempty" jsonschema:"Total number of lines in the file."`
	// Truncated: Whether the file content was truncated due to size limits.
	Truncated bool `json:"truncated,omitempty" jsonschema:"Whether the file content was truncated due to size limits."`
}

// WebFetchArgs defines the arguments for the "web_fetch" tool.
//
// Fetch a web page content.
type WebFetchArgs struct {
	// Url: Web page URL.
	Url string `json:"url" jsonschema:"Web page URL."`
}

// WebFetchOutput defines the output returned by the "web_fetch" tool.
type WebFetchOutput struct {
	// CachedPath: Cached path in workspace session storage.
	CachedPath string `json:"cached_path,omitempty" jsonschema:"Cached path in workspace session storage."`
	// Content: Web page content.
	Content string `json:"content,omitempty" jsonschema:"Web page content."`
	// IsBinary: Whether the fetched file is binary.
	IsBinary bool `json:"is_binary,omitempty" jsonschema:"Whether the fetched file is binary."`
	// MimeType: Detected MIME type.
	MimeType string `json:"mime_type,omitempty" jsonschema:"Detected MIME type."`
	// Title: Web page title.
	Title string `json:"title,omitempty" jsonschema:"Web page title."`
	// Truncated: Whether the content was truncated due to context limits.
	Truncated bool `json:"truncated,omitempty" jsonschema:"Whether the content was truncated due to context limits."`
	// Url: The fetched URL.
	Url string `json:"url,omitempty" jsonschema:"The fetched URL."`
}

// WebSearchArgs defines the arguments for the "web_search" tool.
//
// Search the web.
type WebSearchArgs struct {
	// MaxResults: Maximum number of search results to return (default 10, max 20).
	MaxResults int `json:"max_results,omitempty" jsonschema:"Maximum number of search results to return (default 10, max 20)."`
	// Query: Search query.
	Query string `json:"query" jsonschema:"Search query."`
}

// WebSearchOutput defines the output returned by the "web_search" tool.
type WebSearchOutput struct {
	// Results: Search results.
	Results []WebSearchOutputResultsItem `json:"results,omitempty" jsonschema:"Search results."`
}

type WebSearchOutputResultsItem struct {
	// Snippet: Description or snippet of the search result.
	Snippet string `json:"snippet,omitempty" jsonschema:"Description or snippet of the search result."`
	// Title: Title of the search result.
	Title string `json:"title,omitempty" jsonschema:"Title of the search result."`
	// Url: URL of the search result.
	Url string `json:"url,omitempty" jsonschema:"URL of the search result."`
}

// WriteArgs defines the arguments for the "write" tool.
//
// Write content to a file.
type WriteArgs struct {
	// Content: Content to write.
	Content string `json:"content" jsonschema:"Content to write."`
	// Path: Path to the file.
	Path string `json:"path" jsonschema:"Path to the file."`
}

// WriteOutput defines the output returned by the "write" tool.
type WriteOutput struct {
	// BytesWritten: The number of bytes written to the file.
	BytesWritten int `json:"bytes_written,omitempty" jsonschema:"The number of bytes written to the file."`
	// Path: Path to the written file.
	Path string `json:"path,omitempty" jsonschema:"Path to the written file."`
	// Success: Whether the file was written successfully.
	Success bool `json:"success,omitempty" jsonschema:"Whether the file was written successfully."`
}
