package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type localTool struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	Metadata   struct {
		Name   string            `yaml:"name"`
		Labels map[string]string `yaml:"labels"`
	} `yaml:"metadata"`
	Spec struct {
		Description  string         `yaml:"description"`
		Parameters   map[string]any `yaml:"parameters"`
		OutputSchema map[string]any `yaml:"outputSchema"`
	} `yaml:"spec"`
}

type genConfig struct {
	Tools map[string]struct {
		Parameters map[string]any `yaml:"parameters"`
		Output     map[string]any `yaml:"output"`
	} `yaml:"tools"`
}

type toolGenInfo struct {
	Name        string
	IsStreaming bool
}

func main() {
	// Load config.yaml if exists
	var config genConfig
	configPath := "tools/warp-gen/config.yaml"
	if configData, err := os.ReadFile(configPath); err == nil {
		if err := yaml.Unmarshal(configData, &config); err != nil {
			fmt.Printf("Error parsing generator config: %v\n", err)
			os.Exit(1)
		}
	}

	toolsDir := "internal/agent/tools"

	entries, err := os.ReadDir(toolsDir)
	if err != nil {
		fmt.Printf("Error reading tools dir: %v\n", err)
		os.Exit(1)
	}

	var toolFiles []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".md") {
			toolFiles = append(toolFiles, entry.Name())
		}
	}
	sort.Strings(toolFiles)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/warp-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package tools\n\n")

	var toolsToGen []toolGenInfo

	for _, filename := range toolFiles {
		path := filepath.Join(toolsDir, filename)
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Printf("Error reading file %s: %v\n", filename, err)
			os.Exit(1)
		}

		// Split file content into YAML frontmatter and Markdown body
		parts := strings.SplitN(string(data), "---", 3)
		var yamlPart, markdownPart string
		if len(parts) >= 3 {
			yamlPart = parts[1]
			markdownPart = strings.TrimSpace(parts[2])
		} else {
			// Skip files that do not contain valid frontmatter
			continue
		}

		var tool localTool
		if err := yaml.Unmarshal([]byte(yamlPart), &tool); err != nil {
			fmt.Printf("Error parsing YAML front-matter in %s: %v\n", filename, err)
			os.Exit(1)
		}

		if tool.Kind != "Tool" {
			continue
		}

		// Merge overrides/additions from config
		if toolCfg, ok := config.Tools[tool.Metadata.Name]; ok {
			if len(toolCfg.Parameters) > 0 {
				if tool.Spec.Parameters == nil {
					tool.Spec.Parameters = make(map[string]any)
				}
				mergeMaps(tool.Spec.Parameters, toolCfg.Parameters)
			}
			if len(toolCfg.Output) > 0 {
				if tool.Spec.OutputSchema == nil {
					tool.Spec.OutputSchema = make(map[string]any)
				}
				mergeMaps(tool.Spec.OutputSchema, toolCfg.Output)
			}
		}

		isStreaming := tool.Metadata.Labels["streaming"] == "true"
		toolsToGen = append(toolsToGen, toolGenInfo{
			Name:        tool.Metadata.Name,
			IsStreaming: isStreaming,
		})

		description := tool.Spec.Description
		if markdownPart != "" {
			description = markdownPart
		}

		// Generate Arguments Struct
		structName := toCamelCase(tool.Metadata.Name) + "Args"
		argsDoc := fmt.Sprintf("%s defines the arguments for the %q tool.\n\n%s", structName, tool.Metadata.Name, description)
		generateStructs(&buf, structJob{
			name:   structName,
			schema: tool.Spec.Parameters,
			doc:    argsDoc,
		})

		// Generate Output Struct
		outputStructName := toCamelCase(tool.Metadata.Name) + "Output"
		if len(tool.Spec.OutputSchema) > 0 {
			outputDoc := fmt.Sprintf("%s defines the output returned by the %q tool.", outputStructName, tool.Metadata.Name)
			generateStructs(&buf, structJob{
				name:   outputStructName,
				schema: tool.Spec.OutputSchema,
				doc:    outputDoc,
			})
		} else {
			fmt.Fprintf(&buf, "// %s defines the output returned by the %q tool.\ntype %s struct{}\n\n", outputStructName, tool.Metadata.Name, outputStructName)
		}
	}

	// Format types code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Error formatting generated code: %v\n", err)
		fmt.Println(buf.String())
		os.Exit(1)
	}

	outputPath := filepath.Join(toolsDir, "types.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Printf("Error writing generated code to file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated types for %d tools in %s\n", len(toolFiles), outputPath)

	// Generate handlers.go
	var hBuf bytes.Buffer
	hBuf.WriteString("// Code generated by tools/warp-gen. DO NOT EDIT.\n\n")
	hBuf.WriteString("package tools\n\n")
	hBuf.WriteString("import (\n")
	hBuf.WriteString("\t\"fmt\"\n\n")
	hBuf.WriteString("\t\"github.com/masterkeysrd/loom/tool\"\n")
	hBuf.WriteString("\t\"github.com/masterkeysrd/warp\"\n")
	hBuf.WriteString(")\n\n")

	hBuf.WriteString("// LoomTools returns all builtin tools as Loom tools.\n")
	hBuf.WriteString("func LoomTools(handlers *ToolHandlers) ([]*tool.Tool, error) {\n")
	hBuf.WriteString("\tresources, err := Resources()\n")
	hBuf.WriteString("\tif err != nil {\n")
	hBuf.WriteString("\t\treturn nil, fmt.Errorf(\"failed to load tool resources: %w\", err)\n")
	hBuf.WriteString("\t}\n\n")
	hBuf.WriteString("\tresMap := make(map[string]*warp.Tool)\n")
	hBuf.WriteString("\tfor _, r := range resources {\n")
	hBuf.WriteString("\t\tresMap[r.Metadata.Name] = r\n")
	hBuf.WriteString("\t}\n\n")
	hBuf.WriteString("\tvar list []*tool.Tool\n")

	for _, tInfo := range toolsToGen {
		name := tInfo.Name
		camelName := toCamelCase(name)
		hBuf.WriteString(fmt.Sprintf("\tif res, ok := resMap[%q]; ok {\n", name))
		hBuf.WriteString(fmt.Sprintf("\t\tvar opts []tool.Option\n"))
		hBuf.WriteString(fmt.Sprintf("\t\tif res.Spec.Annotations != nil {\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\topts = append(opts, tool.WithAnnotation(tool.Annotation{\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\t\tIsOpenWorld:  res.Spec.Annotations.IsOpenWorld,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\t\tIsDangerous:  res.Spec.Annotations.IsDangerous,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\t\tIsReadOnly:   res.Spec.Annotations.IsReadOnly,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\t\tIsIdempotent: res.Spec.Annotations.IsIdempotent,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\t\tUserHint:     res.Spec.Annotations.UserHint,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\t}))\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t}\n"))
		if tInfo.IsStreaming {
			hBuf.WriteString(fmt.Sprintf("\t\tt, err := tool.NewStreaming(\n"))
		} else {
			hBuf.WriteString(fmt.Sprintf("\t\tt, err := tool.New(\n"))
		}
		hBuf.WriteString(fmt.Sprintf("\t\t\t%q,\n", name))
		hBuf.WriteString(fmt.Sprintf("\t\t\tres.Metadata.DisplayName,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\tres.Metadata.Description,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\thandlers.%s,\n", camelName))
		hBuf.WriteString(fmt.Sprintf("\t\t\topts...,\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t)\n"))
		hBuf.WriteString(fmt.Sprintf("\t\tif err != nil {\n"))
		hBuf.WriteString(fmt.Sprintf("\t\t\treturn nil, fmt.Errorf(\"failed to create tool %s: %%w\", err)\n", name))
		hBuf.WriteString(fmt.Sprintf("\t\t}\n"))
		hBuf.WriteString(fmt.Sprintf("\t\tlist = append(list, t)\n"))
		hBuf.WriteString(fmt.Sprintf("\t}\n\n"))
	}

	hBuf.WriteString("\treturn list, nil\n")
	hBuf.WriteString("}\n")

	formattedHandlers, err := format.Source(hBuf.Bytes())
	if err != nil {
		fmt.Printf("Error formatting generated handlers code: %v\n", err)
		fmt.Println(hBuf.String())
		os.Exit(1)
	}

	handlersPath := filepath.Join(toolsDir, "handlers.go")
	if err := os.WriteFile(handlersPath, formattedHandlers, 0644); err != nil {
		fmt.Printf("Error writing generated handlers code to file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated handlers for %d tools in %s\n", len(toolsToGen), handlersPath)
}

type structJob struct {
	name   string
	schema map[string]any
	doc    string
}

func generateStructs(buf *bytes.Buffer, initialJob structJob) {
	queue := []structJob{initialJob}
	for i := 0; i < len(queue); i++ {
		job := queue[i]
		writeStruct(buf, job.name, job.schema, job.doc, &queue)
	}
}

func resolveType(parentName, propName string, propVal map[string]any, queue *[]structJob) string {
	propType, _ := propVal["type"].(string)
	switch propType {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "object":
		subStructName := parentName + toCamelCase(propName)
		desc, _ := propVal["description"].(string)
		*queue = append(*queue, structJob{
			name:   subStructName,
			schema: propVal,
			doc:    desc,
		})
		return subStructName
	case "array":
		itemVal, ok := propVal["items"].(map[string]any)
		if !ok {
			return "[]any"
		}
		itemTypeStr := resolveType(parentName, propName+"Item", itemVal, queue)
		return "[]" + itemTypeStr
	default:
		return "any"
	}
}

func writeStruct(buf *bytes.Buffer, name string, schema map[string]any, doc string, queue *[]structJob) {
	if doc != "" {
		lines := strings.Split(doc, "\n")
		for _, line := range lines {
			buf.WriteString(fmt.Sprintf("// %s\n", line))
		}
	}
	buf.WriteString(fmt.Sprintf("type %s struct {\n", name))

	props, ok := schema["properties"].(map[string]any)
	if !ok {
		buf.WriteString("}\n\n")
		return
	}

	requiredList, _ := schema["required"].([]any)
	isRequired := func(field string) bool {
		for _, r := range requiredList {
			if rStr, ok := r.(string); ok && rStr == field {
				return true
			}
		}
		return false
	}

	var keys []string
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		propVal, ok := props[k].(map[string]any)
		if !ok {
			continue
		}

		goType := resolveType(name, k, propVal, queue)

		desc, _ := propVal["description"].(string)
		fieldName := toCamelCase(k)

		jsonTag := k
		if customTag, ok := propVal["json_tag"].(string); ok {
			jsonTag = customTag
		} else if !isRequired(k) {
			jsonTag += ",omitempty"
		}

		if desc != "" {
			buf.WriteString(fmt.Sprintf("\t// %s: %s\n", fieldName, desc))
			buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\" jsonschema:\"%s\"`\n", fieldName, goType, jsonTag, strings.ReplaceAll(desc, "\"", "\\\"")))
		} else {
			buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag))
		}
	}

	buf.WriteString("}\n\n")
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func mergeMaps(dst, src map[string]any) {
	for k, v := range src {
		if srcMap, ok := v.(map[string]any); ok {
			if dstMap, ok := dst[k].(map[string]any); ok {
				mergeMaps(dstMap, srcMap)
				continue
			}
		}
		dst[k] = v
	}
}
