package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type localTool struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	Metadata   struct {
		Name   string            `yaml:"name"`
		Labels map[string]string `yaml:"labels"`
	} `yaml:"metadata"`
	Spec struct {
		Command      []string       `yaml:"command"`
		Description  string         `yaml:"description"`
		Parameters   map[string]any `yaml:"parameters"`
		OutputSchema map[string]any `yaml:"outputSchema"`
	} `yaml:"spec"`
}

func main() {
	toolsDir := "internal/agent/tools"

	entries, err := os.ReadDir(toolsDir)
	if err != nil {
		fmt.Printf("Error reading tools dir: %v\n", err)
		os.Exit(1)
	}

	var toolFiles []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".md") {
			toolFiles = append(toolFiles, entry.Name())
		}
	}
	sort.Strings(toolFiles)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/warp-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package tools\n\n")

	for _, filename := range toolFiles {
		path := filepath.Join(toolsDir, filename)
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Printf("Error reading file %s: %v\n", filename, err)
			os.Exit(1)
		}

		// Split file content into YAML frontmatter and Markdown body
		parts := strings.SplitN(string(data), "---", 3)
		var yamlPart, markdownPart string
		if len(parts) >= 3 {
			yamlPart = parts[1]
			markdownPart = strings.TrimSpace(parts[2])
		} else {
			// Skip files that do not contain valid frontmatter
			continue
		}

		var tool localTool
		if err := yaml.Unmarshal([]byte(yamlPart), &tool); err != nil {
			fmt.Printf("Error parsing YAML front-matter in %s: %v\n", filename, err)
			os.Exit(1)
		}

		if tool.Kind != "Tool" {
			continue
		}

		description := tool.Spec.Description
		if markdownPart != "" {
			description = markdownPart
		}

		// Generate Arguments Struct
		structName := toCamelCase(tool.Metadata.Name) + "Args"
		argsDoc := fmt.Sprintf("%s defines the arguments for the %q tool.\n\n%s", structName, tool.Metadata.Name, description)
		writeStruct(&buf, structName, tool.Spec.Parameters, argsDoc)

		// Generate Output Struct (if outputSchema is declared)
		if len(tool.Spec.OutputSchema) > 0 {
			outputStructName := toCamelCase(tool.Metadata.Name) + "Output"
			outputDoc := fmt.Sprintf("%s defines the output returned by the %q tool.", outputStructName, tool.Metadata.Name)
			writeStruct(&buf, outputStructName, tool.Spec.OutputSchema, outputDoc)
		}
	}

	// Format code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Error formatting generated code: %v\n", err)
		fmt.Println(buf.String())
		os.Exit(1)
	}

	outputPath := filepath.Join(toolsDir, "types.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Printf("Error writing generated code to file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated types for %d tools in %s\n", len(toolFiles), outputPath)
}

func writeStruct(buf *bytes.Buffer, name string, schema map[string]any, doc string) {
	if doc != "" {
		lines := strings.Split(doc, "\n")
		for _, line := range lines {
			buf.WriteString(fmt.Sprintf("// %s\n", line))
		}
	}
	buf.WriteString(fmt.Sprintf("type %s struct {\n", name))

	props, ok := schema["properties"].(map[string]any)
	if !ok {
		buf.WriteString("}\n\n")
		return
	}

	var keys []string
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		propVal, ok := props[k].(map[string]any)
		if !ok {
			continue
		}

		propType, _ := propVal["type"].(string)
		goType := "string"
		switch propType {
		case "string":
			goType = "string"
		case "integer":
			goType = "int"
		case "number":
			goType = "float64"
		case "boolean":
			goType = "bool"
		case "array":
			itemType := "any"
			if itemsMap, ok := propVal["items"].(map[string]any); ok {
				if it, ok := itemsMap["type"].(string); ok {
					switch it {
					case "string":
						itemType = "string"
					case "integer":
						itemType = "int"
					case "number":
						itemType = "float64"
					case "boolean":
						itemType = "bool"
					}
				}
			}
			goType = "[]" + itemType
		}

		desc, _ := propVal["description"].(string)
		fieldName := toCamelCase(k)

		if desc != "" {
			buf.WriteString(fmt.Sprintf("\t// %s: %s\n", fieldName, desc))
		}
		buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", fieldName, goType, k))
	}

	buf.WriteString("}\n\n")
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}
